### ISSUE TITLE
Calls to application API generate error when in maintenance

### ISSUE THREAD

**Issue by treydock** [biola/turnout#23]
I have an application that has an API backend that uses versioning and have noticed when I put the application into maintenance using turnout the API calls generate exceptions.

This is the exception generated:

```
A RuntimeError occurred in #:

  Invalid header value: "application/emop; version=1"
  config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'
```

The code using the API is setting the "Accept" HTTP header to be "application/emop; version=1".

The Rails application is here - https://github.com/Early-Modern-OCR/emop-dashboard

Let me know if this is specific to turnout or if this could be caused by another issue.  The issue only happens when maintenance is enabled.

Thanks,
- Trey

**Comment by adamcrown** [comment]
It looks like this is actually a problem with [rack-accept](https://github.com/mjackson/rack-accept). I'd suggest opening an issue over there.

Looks like [this is where the error is being raised](https://github.com/mjackson/rack-accept/blob/031dd2e3ad2a3769c81c6c2c394070589e2c989c/lib/rack/accept/header.rb#L19).

You'll notice that if you run your accept header against the [regex  it's using](https://github.com/mjackson/rack-accept/blob/031dd2e3ad2a3769c81c6c2c394070589e2c989c/lib/rack/accept/header.rb#L14), it doesn't match. However, removing the space seems to fix it if you're looking for an easy workaround.
```ruby
/^([^\s,]+?)(?:\s*;\s*q\s*=\s*(\d+(?:\.\d+)?))?$/.match('application/emop; version=1') #=> nil
/^([^\s,]+?)(?:\s*;\s*q\s*=\s*(\d+(?:\.\d+)?))?$/.match('application/emop;version=1') #=> #<MatchData "application/emop;version=1" 1:"application/emop;version=1" 2:nil>
```
