### ISSUE TITLE
Add support for redis/db backed configuration

### ISSUE THREAD

**Issue by kozze89** [biola/turnout#31]
I am running multiple rails servers, it would be awesome if this configuration was hosted in redis. Perhaps multiple other backends as well. Currently I have to enable maintenance mode on each node.

**Comment by adamcrown** [comment]
I can see the appeal and that is a great idea. I'd be happy to take a pull request for something like that as long as it doesn't add a lot of new dependencies. At it's hart I want turnout to remain a simple tool to use that doesn't take a lot of setup. But an optional feature like that for more advanced users could be nice.

In the meantime, here are a couple suggestions that might help you out.
- This is mentioned in the README, but you can setup custom maintenance file paths with `named_maintenance_file_paths`. If you have a path that is shared between your servers then you can put them all in maintenance mode at once.
- Another option is something like pssh or fabric to trigger a rake maintenance:start` on all your servers. I've used fabric before and it's very easy to setup.

**Comment by kozze89** [comment]
Thanks for the suggestions @adamcrown. I would love to make a PR, but I really really don't have the time right now sorry. Closing this ticket for now.
