### ISSUE TITLE
Maintenance helper

### ISSUE THREAD

**Issue by RichieAHB** [biola/turnout#36]
I was wondering if there was a helper or something similar that I could use to display a UI hint in the application layout that maintenance mode is activated.  Obviously that would be for those IPs that had been permitted.

**Comment by adamcrown** [comment]
I can't see any reason you can't use `Turnout::MaintenanceFile.find.present?` to check if the maintenance file exists. Let me know if that doesn't work for you for any reason.

**Comment by adamcrown** [comment]
I just added this to the README in the Tips section in case it might be helpful to anybody else.
