### ISSUE TITLE
Any way to redirect to a subdominant?

### ISSUE THREAD

**Issue by CiaranPearse** [biola/turnout#38]
Is there any way to redirect users to a subdomain when maintenance is on? Let's say instead of a maintainance page they could be redirected to signup.xxxxxxxx.com. 

It would be very useful to get a prod env working correctly before allowing access to it. 

Great gem btw :)

**Comment by adamcrown** [comment]
The easiest way would be to setup a meta redirect. Just create your own `public/maintenance.html` file and add something like this inside the `<head>` tag.

```html
<meta http-equiv="refresh" content="0; url=http://example.com/" />
```
