### ISSUE TITLE
Rake task is not "grepable"

### ISSUE THREAD

**Issue by stereobooster** [biola/turnout#42]
```
bundle exec rake -T | grep maintenance
# nothing
bundle exec rake -W maintenance:start
# nothing
bundle exec rake maintenance:start
# works just fine
```

Took me some time to find out what is going on.

**Comment by adamcrown** [comment]
Yeah, that's unfortunate. It's because turnout uses rake rules rather rather than rake tasks. I went into some detail on it in an [earlier issue](https://github.com/biola/turnout/issues/26).
