### ISSUE TITLE
Need to restart rails app to make it work.

### ISSUE THREAD

**Issue by nik-007** [biola/turnout#47]
The gem works fabulously but in my development env I had to restart the server to make this maintenance mode work. why is this happening? will it work fine on production env?

**Comment by nik-007** [comment]
Sorry my bad, It started working.

**Comment by mikeymicrophone** [comment]
This was helpful for me.  Even though I've been using Rails for 12 years and should have known to restart my server after installing a gem.  MIGHT be worth mentioning in the readme.

**Comment by adamcrown** [comment]
That's a good idea. I'll add it to the README.
