### ISSUE TITLE
Add support for i18n

### ISSUE THREAD

**Issue by coorasse** [biola/turnout#9]
At least an how to, because it's a static page so we'll have to do it by JS I think

**Comment by abitdodgy** [comment]
@adamcrown is it possible to configure turnout to just redirect to a specified path? Let's say I prepare a `maintenance_mode_path`. How can I configure turnout to just redirect there? This would solve the I18n issue too since one could just use Rails I18n in the view template.

**Comment by adamcrown** [comment]
@abitdodgy well the easy way would be to just put a `<meta>` refresh tag in the HTML `maitenance.html` page. Such as

```html
<meta http-equiv="refresh" content="0; url=http://example.com" />
```

**Comment by bogdanRada** [comment]
Turnout supports now ERB templates so you could use this gem https://github.com/svenfuchs/i18n , and i think the best way would be to have  a middleware inserted before the Turnout Middleware that could set the correct language properties and in view you could just use it.

**Comment by abitdodgy** [comment]
Nice. [I ended up rolling my own solution](http://blog.mohamad.im/2015/08/30/adding-a-dynamic-maintenance-mode-to-your-rails-app.html), though. In the end, it was more disrable for our use case.

**Comment by bogdanRada** [comment]
that looks like a lot of work for something that could have been made in a few lines of code. Glad though that it works for you :)

**Comment by abitdodgy** [comment]
@bogdanRada at the time it wasn't possible to serve I18n pages, so we had to roll our own.

**Comment by bogdanRada** [comment]
yes, i understand. Just wanted to give you a bit of help and i thought maybe you would be interested in a better way of handling that with the newest version.

**Comment by bogdanRada** [comment]
I added support for I18n in this pull request https://github.com/biola/turnout/pull/37 , but i got no feedback in more than two months. Can somebody please check it out ? Or at least tell me if you are not interested in this anymore. Thank you very much.

**Comment by adamcrown** [comment]
i18n was added in #37 and version 2.4.0. Thanks @bogdanRada!
